
const int keymap_default[128] = {
	0,                        // ---- ---
	0,                        // ---- --F
	KEY_SPACE,                // ---- -T-
	0,                        // ---- -TF
	0,                        // ---- N--
	0,                        // ---- N-F
	0,                        // ---- NT-
	0,                        // ---- NTF
	KEY_E,                    // ---I ---
	KEY_M,                    // ---I --F
	KEY_L,                    // ---I -T-
	0,                        // ---I -TF
	0,                        // ---I N--
	0,                        // ---I N-F
	0,                        // ---I NT-
	0,                        // ---I NTF
	KEY_T,                    // --M- ---
	KEY_BACKSPACE,            // --M- --F
	KEY_D,                    // --M- -T-
	0,                        // --M- -TF
	0,                        // --M- N--
	0,                        // --M- N-F
	0,                        // --M- NT-
	0,                        // --M- NTF
	KEY_I,                    // --MI ---
	0,                        // --MI --F
	KEY_V,                    // --MI -T-
	0,                        // --MI -TF
	0,                        // --MI N--
	0,                        // --MI N-F
	0,                        // --MI NT-
	0,                        // --MI NTF
	KEY_A,                    // -R-- ---
	KEY_F,                    // -R-- --F
	KEY_C,                    // -R-- -T-
	0,                        // -R-- -TF
	0,                        // -R-- N--
	0,                        // -R-- N-F
	0,                        // -R-- NT-
	0,                        // -R-- NTF
	KEY_R,                    // -R-I ---
	0,                        // -R-I --F
	KEY_J,                    // -R-I -T-
	0,                        // -R-I -TF
	0,                        // -R-I N--
	0,                        // -R-I N-F
	0,                        // -R-I NT-
	0,                        // -R-I NTF
	KEY_N,                    // -RM- ---
	KEY_DELETE,               // -RM- --F
	KEY_K,                    // -RM- -T-
	0,                        // -RM- -TF
	0,                        // -RM- N--
	0,                        // -RM- N-F
	0,                        // -RM- NT-
	0,                        // -RM- NTF
	KEY_G,                    // -RMI ---
	0,                        // -RMI --F
	0,                        // -RMI -T-
	0,                        // -RMI -TF
	0,                        // -RMI N--
	0,                        // -RMI N-F
	0,                        // -RMI NT-
	0,                        // -RMI NTF
	KEY_O,                    // P--- ---
	KEY_P,                    // P--- --F
	KEY_U,                    // P--- -T-
	0,                        // P--- -TF
	0,                        // P--- N--
	0,                        // P--- N-F
	0,                        // P--- NT-
	0,                        // P--- NTF
	0,                        // P--I ---
	KEY_ENTER,                // P--I --F
	KEY_Z,                    // P--I -T-
	0,                        // P--I -TF
	0,                        // P--I N--
	0,                        // P--I N-F
	0,                        // P--I NT-
	0,                        // P--I NTF
	KEY_H,                    // P-M- ---
	0,                        // P-M- --F
	KEY_Q,                    // P-M- -T-
	0,                        // P-M- -TF
	0,                        // P-M- N--
	0,                        // P-M- N-F
	0,                        // P-M- NT-
	0,                        // P-M- NTF
	KEY_W,                    // P-MI ---
	0,                        // P-MI --F
	0,                        // P-MI -T-
	0,                        // P-MI -TF
	0,                        // P-MI N--
	0,                        // P-MI N-F
	0,                        // P-MI NT-
	0,                        // P-MI NTF
	KEY_S,                    // PR-- ---
	0,                        // PR-- --F
	KEY_X,                    // PR-- -T-
	0,                        // PR-- -TF
	0,                        // PR-- N--
	0,                        // PR-- N-F
	0,                        // PR-- NT-
	0,                        // PR-- NTF
	KEY_Y,                    // PR-I ---
	0,                        // PR-I --F
	0,                        // PR-I -T-
	0,                        // PR-I -TF
	0,                        // PR-I N--
	0,                        // PR-I N-F
	0,                        // PR-I NT-
	0,                        // PR-I NTF
	KEY_B,                    // PRM- ---
	0,                        // PRM- --F
	0,                        // PRM- -T-
	0,                        // PRM- -TF
	0,                        // PRM- N--
	0,                        // PRM- N-F
	0,                        // PRM- NT-
	0,                        // PRM- NTF
	0,                        // PRMI ---
	0,                        // PRMI --F
	0,                        // PRMI -T-
	0,                        // PRMI -TF
	0,                        // PRMI N--
	0,                        // PRMI N-F
	0,                        // PRMI NT-
	0                         // PRMI NTF
};